use_frameworks!

target 'SimpleRealm_Example' do
  pod 'SimpleRealm', :git => 'https://github.com/amrOmran89/SimpleRealm_iOS.git'

  target 'SimpleRealm_Tests' do
    inherit! :search_paths

    
  end
end
